### ISSUE TITLE
Support EL8 and EL9 for basic configurations

### ISSUE THREAD

**Issue by ghomem** [ghomem/puppet_infrastructure#5]
Wee need to support EL8 and EL9 for at least:

* node_base
* nginx_static
* nginx_frontend

**Comment by PrinceSalatyell** [comment]
Currently, the node base is working well on RHEL, but mcollective had to be disabled for these machines, because there is no support for the at all. The puppet-agent installation, on ubuntu already automatically installs mcollective, but on RHEL it doesn't. There is no trace of mcollective in the yum repos and I even tried using the puppet-mcollective module, but it fails miserably.

Right now, mcollective_master is even having issues being ran on ubuntu 22 masters. It might be time to consider an alternative, as mcollective seems to be more of an issue than a benefit at this point.

**Comment by ghomem** [comment]
OK, let's go with basic Puppet support first. Can you produce the PR please?

**Comment by PrinceSalatyell** [comment]
link to PR: https://github.com/ghomem/puppet_infrastructure/pull/7

This was approved and merged. 
Closing the issue.
